version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: pathshala-postgres
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: pathshala_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pathshala-network

volumes:
  postgres_data:

networks:
  pathshala-network:
    driver: bridge